- name: Install packages
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: Install docker-ce
  ansible.builtin.apt:
    name: docker-ce
    state: present

- name: Install Docker Module for Python
  ansible.builtin.pip:
    name: docker

- name: Copy docker-compose.yml
  ansible.builtin.copy:
    src: ../postgres-docker/docker-compose.yml
    dest: /home/jack/docker-compose.yml
    mode: "0644"

- name: Start Docker Compose services
  ansible.builtin.command: docker compose up -d
  args:
    chdir: /home/jack/
  register: my_output
  changed_when: my_output.rc != 0
