name: actionlint

"on":
  push:
    branches: [testing]
    paths: [".github/**/*.yml"]

jobs:
  run-actionlint:
    runs-on: ubuntu-latest
    permissions:
      # needed for the checkout action
      contents: read
    steps:
      # checkout the source code to analyze
      - uses: actions/checkout@v4

      # run the actionlinter, will fail on errors
      - uses: devops-actions/actionlint@c0ee017f8abef55d843a647cd737b87a1976eb69
# test
