name: Tflint

"on":
  push:
    branches: [testing]
    paths: ["Terraform/**/*.tf"]
  pull_request:
    branches: [main]

jobs:
  tflint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout source code

      - uses: terraform-linters/setup-tflint@v4
        name: Setup TFLint
        with:
          tflint_version: v0.50.3

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        working-directory: ./Terraform
        run: tflint --init
        env:
          # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
          GITHUB_TOKEN: ${{ github.token }}

      - uses: terraform-linters/setup-tflint@v4
        with:
          tflint_wrapper: true

      - id: tflint
        working-directory: ./Terraform
        run: tflint -f compact

      - run: echo ${{ steps.tflint.outputs.stdout }}
      - run: echo ${{ steps.tflint.outputs.stderr }}
      - run: echo ${{ steps.tflint.outputs.exitcode }}
d